#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TuyenSinh")]
	public partial class QuanLiTuyenSinhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertDanhSachUngTuyen(DanhSachUngTuyen instance);
    partial void UpdateDanhSachUngTuyen(DanhSachUngTuyen instance);
    partial void DeleteDanhSachUngTuyen(DanhSachUngTuyen instance);
    partial void InsertHeDaoTao(HeDaoTao instance);
    partial void UpdateHeDaoTao(HeDaoTao instance);
    partial void DeleteHeDaoTao(HeDaoTao instance);
    partial void InsertHocPhiHocBong(HocPhiHocBong instance);
    partial void UpdateHocPhiHocBong(HocPhiHocBong instance);
    partial void DeleteHocPhiHocBong(HocPhiHocBong instance);
    partial void InsertLienHe(LienHe instance);
    partial void UpdateLienHe(LienHe instance);
    partial void DeleteLienHe(LienHe instance);
    partial void InsertPhuongThucXetTuyen(PhuongThucXetTuyen instance);
    partial void UpdatePhuongThucXetTuyen(PhuongThucXetTuyen instance);
    partial void DeletePhuongThucXetTuyen(PhuongThucXetTuyen instance);
    partial void InsertTimeLine(TimeLine instance);
    partial void UpdateTimeLine(TimeLine instance);
    partial void DeleteTimeLine(TimeLine instance);
    partial void InsertTinTuyenSinh(TinTuyenSinh instance);
    partial void UpdateTinTuyenSinh(TinTuyenSinh instance);
    partial void DeleteTinTuyenSinh(TinTuyenSinh instance);
    partial void InsertThongTinChung(ThongTinChung instance);
    partial void UpdateThongTinChung(ThongTinChung instance);
    partial void DeleteThongTinChung(ThongTinChung instance);
    partial void InsertThongTinChuyenNganh(ThongTinChuyenNganh instance);
    partial void UpdateThongTinChuyenNganh(ThongTinChuyenNganh instance);
    partial void DeleteThongTinChuyenNganh(ThongTinChuyenNganh instance);
    partial void InsertThongTinNguoiDung(ThongTinNguoiDung instance);
    partial void UpdateThongTinNguoiDung(ThongTinNguoiDung instance);
    partial void DeleteThongTinNguoiDung(ThongTinNguoiDung instance);
    partial void InsertThongTinNhapHoc(ThongTinNhapHoc instance);
    partial void UpdateThongTinNhapHoc(ThongTinNhapHoc instance);
    partial void DeleteThongTinNhapHoc(ThongTinNhapHoc instance);
    partial void InsertThongTinVanBan(ThongTinVanBan instance);
    partial void UpdateThongTinVanBan(ThongTinVanBan instance);
    partial void DeleteThongTinVanBan(ThongTinVanBan instance);
    #endregion
		
		public QuanLiTuyenSinhDataContext() : 
				base(global::UI.Properties.Settings.Default.TuyenSinhConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiTuyenSinhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiTuyenSinhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiTuyenSinhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiTuyenSinhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<ChuongTrinhDaoTao> ChuongTrinhDaoTaos
		{
			get
			{
				return this.GetTable<ChuongTrinhDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachUngTuyen> DanhSachUngTuyens
		{
			get
			{
				return this.GetTable<DanhSachUngTuyen>();
			}
		}
		
		public System.Data.Linq.Table<HeDaoTao> HeDaoTaos
		{
			get
			{
				return this.GetTable<HeDaoTao>();
			}
		}
		
		public System.Data.Linq.Table<HocPhiHocBong> HocPhiHocBongs
		{
			get
			{
				return this.GetTable<HocPhiHocBong>();
			}
		}
		
		public System.Data.Linq.Table<LienHe> LienHes
		{
			get
			{
				return this.GetTable<LienHe>();
			}
		}
		
		public System.Data.Linq.Table<PhuongThucXetTuyen> PhuongThucXetTuyens
		{
			get
			{
				return this.GetTable<PhuongThucXetTuyen>();
			}
		}
		
		public System.Data.Linq.Table<TimeLine> TimeLines
		{
			get
			{
				return this.GetTable<TimeLine>();
			}
		}
		
		public System.Data.Linq.Table<TinTuyenSinh> TinTuyenSinhs
		{
			get
			{
				return this.GetTable<TinTuyenSinh>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinChung> ThongTinChungs
		{
			get
			{
				return this.GetTable<ThongTinChung>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinChuyenNganh> ThongTinChuyenNganhs
		{
			get
			{
				return this.GetTable<ThongTinChuyenNganh>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinKhoa> ThongTinKhoas
		{
			get
			{
				return this.GetTable<ThongTinKhoa>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinNguoiDung> ThongTinNguoiDungs
		{
			get
			{
				return this.GetTable<ThongTinNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinNhapHoc> ThongTinNhapHocs
		{
			get
			{
				return this.GetTable<ThongTinNhapHoc>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinVanBan> ThongTinVanBans
		{
			get
			{
				return this.GetTable<ThongTinVanBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuongTrinhDaoTao")]
	public partial class ChuongTrinhDaoTao
	{
		
		private string _TenChuongTrinh;
		
		private string _NganhDaoTao;
		
		private string _HeDaoTao;
		
		private string _PDFDaoTao;
		
		private string _NoiDung;
		
		public ChuongTrinhDaoTao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuongTrinh", DbType="NVarChar(MAX)")]
		public string TenChuongTrinh
		{
			get
			{
				return this._TenChuongTrinh;
			}
			set
			{
				if ((this._TenChuongTrinh != value))
				{
					this._TenChuongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhDaoTao", DbType="NVarChar(50)")]
		public string NganhDaoTao
		{
			get
			{
				return this._NganhDaoTao;
			}
			set
			{
				if ((this._NganhDaoTao != value))
				{
					this._NganhDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeDaoTao", DbType="NVarChar(50)")]
		public string HeDaoTao
		{
			get
			{
				return this._HeDaoTao;
			}
			set
			{
				if ((this._HeDaoTao != value))
				{
					this._HeDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFDaoTao", DbType="NVarChar(MAX)")]
		public string PDFDaoTao
		{
			get
			{
				return this._PDFDaoTao;
			}
			set
			{
				if ((this._PDFDaoTao != value))
				{
					this._PDFDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachUngTuyen")]
	public partial class DanhSachUngTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HoTen;
		
		private string _Email;
		
		private string _SDT;
		
		private System.Nullable<int> _MaHoSo;
		
		private System.Nullable<int> _MaNguyenVong;
		
		private string _NganhUngTuyen;
		
		private string _TrangThai;
		
		private string _PhuongThuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMaHoSoChanging(System.Nullable<int> value);
    partial void OnMaHoSoChanged();
    partial void OnMaNguyenVongChanging(System.Nullable<int> value);
    partial void OnMaNguyenVongChanged();
    partial void OnNganhUngTuyenChanging(string value);
    partial void OnNganhUngTuyenChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnPhuongThucChanging(string value);
    partial void OnPhuongThucChanged();
    #endregion
		
		public DanhSachUngTuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoSo", DbType="Int", IsPrimaryKey=true)]
		public System.Nullable<int> MaHoSo
		{
			get
			{
				return this._MaHoSo;
			}
			set
			{
				if ((this._MaHoSo != value))
				{
					this.OnMaHoSoChanging(value);
					this.SendPropertyChanging();
					this._MaHoSo = value;
					this.SendPropertyChanged("MaHoSo");
					this.OnMaHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguyenVong", DbType="Int")]
		public System.Nullable<int> MaNguyenVong
		{
			get
			{
				return this._MaNguyenVong;
			}
			set
			{
				if ((this._MaNguyenVong != value))
				{
					this.OnMaNguyenVongChanging(value);
					this.SendPropertyChanging();
					this._MaNguyenVong = value;
					this.SendPropertyChanged("MaNguyenVong");
					this.OnMaNguyenVongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhUngTuyen", DbType="NVarChar(50)")]
		public string NganhUngTuyen
		{
			get
			{
				return this._NganhUngTuyen;
			}
			set
			{
				if ((this._NganhUngTuyen != value))
				{
					this.OnNganhUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._NganhUngTuyen = value;
					this.SendPropertyChanged("NganhUngTuyen");
					this.OnNganhUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(20)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThuc", DbType="NVarChar(50)")]
		public string PhuongThuc
		{
			get
			{
				return this._PhuongThuc;
			}
			set
			{
				if ((this._PhuongThuc != value))
				{
					this.OnPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._PhuongThuc = value;
					this.SendPropertyChanged("PhuongThuc");
					this.OnPhuongThucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeDaoTao")]
	public partial class HeDaoTao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHeDaoTao;
		
		private string _TenHeDaoTao;
		
		private string _GioiThieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHeDaoTaoChanging(string value);
    partial void OnMaHeDaoTaoChanged();
    partial void OnTenHeDaoTaoChanging(string value);
    partial void OnTenHeDaoTaoChanged();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    #endregion
		
		public HeDaoTao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHeDaoTao", DbType="NVarChar(20)", IsPrimaryKey=true)]
		public string MaHeDaoTao
		{
			get
			{
				return this._MaHeDaoTao;
			}
			set
			{
				if ((this._MaHeDaoTao != value))
				{
					this.OnMaHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._MaHeDaoTao = value;
					this.SendPropertyChanged("MaHeDaoTao");
					this.OnMaHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHeDaoTao", DbType="NVarChar(20)")]
		public string TenHeDaoTao
		{
			get
			{
				return this._TenHeDaoTao;
			}
			set
			{
				if ((this._TenHeDaoTao != value))
				{
					this.OnTenHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._TenHeDaoTao = value;
					this.SendPropertyChanged("TenHeDaoTao");
					this.OnTenHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(20)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocPhiHocBong")]
	public partial class HocPhiHocBong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public HocPhiHocBong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)", IsPrimaryKey=true)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LienHe")]
	public partial class LienHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DiaDiem;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _Fanpage;
		
		private string _PhongBanLienHe;
		
		private string _VanPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFanpageChanging(string value);
    partial void OnFanpageChanged();
    partial void OnPhongBanLienHeChanging(string value);
    partial void OnPhongBanLienHeChanged();
    partial void OnVanPhongChanging(string value);
    partial void OnVanPhongChanged();
    #endregion
		
		public LienHe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(50)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fanpage", DbType="NVarChar(50)")]
		public string Fanpage
		{
			get
			{
				return this._Fanpage;
			}
			set
			{
				if ((this._Fanpage != value))
				{
					this.OnFanpageChanging(value);
					this.SendPropertyChanging();
					this._Fanpage = value;
					this.SendPropertyChanged("Fanpage");
					this.OnFanpageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBanLienHe", DbType="NVarChar(50)")]
		public string PhongBanLienHe
		{
			get
			{
				return this._PhongBanLienHe;
			}
			set
			{
				if ((this._PhongBanLienHe != value))
				{
					this.OnPhongBanLienHeChanging(value);
					this.SendPropertyChanging();
					this._PhongBanLienHe = value;
					this.SendPropertyChanged("PhongBanLienHe");
					this.OnPhongBanLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanPhong", DbType="NVarChar(20)")]
		public string VanPhong
		{
			get
			{
				return this._VanPhong;
			}
			set
			{
				if ((this._VanPhong != value))
				{
					this.OnVanPhongChanging(value);
					this.SendPropertyChanging();
					this._VanPhong = value;
					this.SendPropertyChanged("VanPhong");
					this.OnVanPhongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhuongThucXetTuyen")]
	public partial class PhuongThucXetTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenPhuongThuc;
		
		private string _MaPhuongThuc;
		
		private string _HeDaoTao;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private string _HinhAnh;
		
		private string _NoiDung;
		
		private string _PhuongThucCha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenPhuongThucChanging(string value);
    partial void OnTenPhuongThucChanged();
    partial void OnMaPhuongThucChanging(string value);
    partial void OnMaPhuongThucChanged();
    partial void OnHeDaoTaoChanging(string value);
    partial void OnHeDaoTaoChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnPhuongThucChaChanging(string value);
    partial void OnPhuongThucChaChanged();
    #endregion
		
		public PhuongThucXetTuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuongThuc", DbType="NVarChar(50)")]
		public string TenPhuongThuc
		{
			get
			{
				return this._TenPhuongThuc;
			}
			set
			{
				if ((this._TenPhuongThuc != value))
				{
					this.OnTenPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._TenPhuongThuc = value;
					this.SendPropertyChanged("TenPhuongThuc");
					this.OnTenPhuongThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongThuc", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string MaPhuongThuc
		{
			get
			{
				return this._MaPhuongThuc;
			}
			set
			{
				if ((this._MaPhuongThuc != value))
				{
					this.OnMaPhuongThucChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongThuc = value;
					this.SendPropertyChanged("MaPhuongThuc");
					this.OnMaPhuongThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeDaoTao", DbType="NVarChar(50)")]
		public string HeDaoTao
		{
			get
			{
				return this._HeDaoTao;
			}
			set
			{
				if ((this._HeDaoTao != value))
				{
					this.OnHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._HeDaoTao = value;
					this.SendPropertyChanged("HeDaoTao");
					this.OnHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucCha", DbType="NVarChar(50)")]
		public string PhuongThucCha
		{
			get
			{
				return this._PhuongThucCha;
			}
			set
			{
				if ((this._PhuongThucCha != value))
				{
					this.OnPhuongThucChaChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucCha = value;
					this.SendPropertyChanged("PhuongThucCha");
					this.OnPhuongThucChaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TimeLine")]
	public partial class TimeLine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenSuKien;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private string _HeDaoTao;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenSuKienChanging(string value);
    partial void OnTenSuKienChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnHeDaoTaoChanging(string value);
    partial void OnHeDaoTaoChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public TimeLine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSuKien", DbType="NVarChar(20)", IsPrimaryKey=true)]
		public string TenSuKien
		{
			get
			{
				return this._TenSuKien;
			}
			set
			{
				if ((this._TenSuKien != value))
				{
					this.OnTenSuKienChanging(value);
					this.SendPropertyChanging();
					this._TenSuKien = value;
					this.SendPropertyChanged("TenSuKien");
					this.OnTenSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeDaoTao", DbType="NVarChar(20)")]
		public string HeDaoTao
		{
			get
			{
				return this._HeDaoTao;
			}
			set
			{
				if ((this._HeDaoTao != value))
				{
					this.OnHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._HeDaoTao = value;
					this.SendPropertyChanged("HeDaoTao");
					this.OnHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuyenSinh")]
	public partial class TinTuyenSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private string _HeDaoTao;
		
		private string _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnHeDaoTaoChanging(string value);
    partial void OnHeDaoTaoChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public TinTuyenSinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(20)", IsPrimaryKey=true)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(50)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeDaoTao", DbType="NVarChar(20)")]
		public string HeDaoTao
		{
			get
			{
				return this._HeDaoTao;
			}
			set
			{
				if ((this._HeDaoTao != value))
				{
					this.OnHeDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._HeDaoTao = value;
					this.SendPropertyChanged("HeDaoTao");
					this.OnHeDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(20)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinChung")]
	public partial class ThongTinChung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GioiThieuTruong;
		
		private System.Nullable<int> _SoGiaoSu;
		
		private System.Nullable<int> _SoPhoGiaoSu;
		
		private System.Nullable<int> _SoThacSiTienSi;
		
		private System.Nullable<int> _SoNganhDaoTaoTienSi;
		
		private System.Nullable<int> _SoNganhDaoTaoThacSi;
		
		private System.Nullable<int> _SoNganhDaoTaoCuNhan;
		
		private string _VideoGioiThieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGioiThieuTruongChanging(string value);
    partial void OnGioiThieuTruongChanged();
    partial void OnSoGiaoSuChanging(System.Nullable<int> value);
    partial void OnSoGiaoSuChanged();
    partial void OnSoPhoGiaoSuChanging(System.Nullable<int> value);
    partial void OnSoPhoGiaoSuChanged();
    partial void OnSoThacSiTienSiChanging(System.Nullable<int> value);
    partial void OnSoThacSiTienSiChanged();
    partial void OnSoNganhDaoTaoTienSiChanging(System.Nullable<int> value);
    partial void OnSoNganhDaoTaoTienSiChanged();
    partial void OnSoNganhDaoTaoThacSiChanging(System.Nullable<int> value);
    partial void OnSoNganhDaoTaoThacSiChanged();
    partial void OnSoNganhDaoTaoCuNhanChanging(System.Nullable<int> value);
    partial void OnSoNganhDaoTaoCuNhanChanged();
    partial void OnVideoGioiThieuChanging(string value);
    partial void OnVideoGioiThieuChanged();
    #endregion
		
		public ThongTinChung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieuTruong", DbType="NVarChar(MAX)", IsPrimaryKey=true)]
		public string GioiThieuTruong
		{
			get
			{
				return this._GioiThieuTruong;
			}
			set
			{
				if ((this._GioiThieuTruong != value))
				{
					this.OnGioiThieuTruongChanging(value);
					this.SendPropertyChanging();
					this._GioiThieuTruong = value;
					this.SendPropertyChanged("GioiThieuTruong");
					this.OnGioiThieuTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGiaoSu", DbType="Int")]
		public System.Nullable<int> SoGiaoSu
		{
			get
			{
				return this._SoGiaoSu;
			}
			set
			{
				if ((this._SoGiaoSu != value))
				{
					this.OnSoGiaoSuChanging(value);
					this.SendPropertyChanging();
					this._SoGiaoSu = value;
					this.SendPropertyChanged("SoGiaoSu");
					this.OnSoGiaoSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhoGiaoSu", DbType="Int")]
		public System.Nullable<int> SoPhoGiaoSu
		{
			get
			{
				return this._SoPhoGiaoSu;
			}
			set
			{
				if ((this._SoPhoGiaoSu != value))
				{
					this.OnSoPhoGiaoSuChanging(value);
					this.SendPropertyChanging();
					this._SoPhoGiaoSu = value;
					this.SendPropertyChanged("SoPhoGiaoSu");
					this.OnSoPhoGiaoSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThacSiTienSi", DbType="Int")]
		public System.Nullable<int> SoThacSiTienSi
		{
			get
			{
				return this._SoThacSiTienSi;
			}
			set
			{
				if ((this._SoThacSiTienSi != value))
				{
					this.OnSoThacSiTienSiChanging(value);
					this.SendPropertyChanging();
					this._SoThacSiTienSi = value;
					this.SendPropertyChanged("SoThacSiTienSi");
					this.OnSoThacSiTienSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNganhDaoTaoTienSi", DbType="Int")]
		public System.Nullable<int> SoNganhDaoTaoTienSi
		{
			get
			{
				return this._SoNganhDaoTaoTienSi;
			}
			set
			{
				if ((this._SoNganhDaoTaoTienSi != value))
				{
					this.OnSoNganhDaoTaoTienSiChanging(value);
					this.SendPropertyChanging();
					this._SoNganhDaoTaoTienSi = value;
					this.SendPropertyChanged("SoNganhDaoTaoTienSi");
					this.OnSoNganhDaoTaoTienSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNganhDaoTaoThacSi", DbType="Int")]
		public System.Nullable<int> SoNganhDaoTaoThacSi
		{
			get
			{
				return this._SoNganhDaoTaoThacSi;
			}
			set
			{
				if ((this._SoNganhDaoTaoThacSi != value))
				{
					this.OnSoNganhDaoTaoThacSiChanging(value);
					this.SendPropertyChanging();
					this._SoNganhDaoTaoThacSi = value;
					this.SendPropertyChanged("SoNganhDaoTaoThacSi");
					this.OnSoNganhDaoTaoThacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNganhDaoTaoCuNhan", DbType="Int")]
		public System.Nullable<int> SoNganhDaoTaoCuNhan
		{
			get
			{
				return this._SoNganhDaoTaoCuNhan;
			}
			set
			{
				if ((this._SoNganhDaoTaoCuNhan != value))
				{
					this.OnSoNganhDaoTaoCuNhanChanging(value);
					this.SendPropertyChanging();
					this._SoNganhDaoTaoCuNhan = value;
					this.SendPropertyChanged("SoNganhDaoTaoCuNhan");
					this.OnSoNganhDaoTaoCuNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoGioiThieu", DbType="NVarChar(MAX)")]
		public string VideoGioiThieu
		{
			get
			{
				return this._VideoGioiThieu;
			}
			set
			{
				if ((this._VideoGioiThieu != value))
				{
					this.OnVideoGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._VideoGioiThieu = value;
					this.SendPropertyChanged("VideoGioiThieu");
					this.OnVideoGioiThieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinChuyenNganh")]
	public partial class ThongTinChuyenNganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNganh;
		
		private string _TenNganh;
		
		private string _LoaiChuongTrinh;
		
		private string _Khoa;
		
		private System.Nullable<int> _ChiTieu;
		
		private System.Nullable<int> _HocPhi;
		
		private string _MoTaNganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    partial void OnTenNganhChanging(string value);
    partial void OnTenNganhChanged();
    partial void OnLoaiChuongTrinhChanging(string value);
    partial void OnLoaiChuongTrinhChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    partial void OnChiTieuChanging(System.Nullable<int> value);
    partial void OnChiTieuChanged();
    partial void OnHocPhiChanging(System.Nullable<int> value);
    partial void OnHocPhiChanged();
    partial void OnMoTaNganhChanging(string value);
    partial void OnMoTaNganhChanged();
    #endregion
		
		public ThongTinChuyenNganh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(50)")]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this.OnTenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenNganh = value;
					this.SendPropertyChanged("TenNganh");
					this.OnTenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiChuongTrinh", DbType="NVarChar(50)")]
		public string LoaiChuongTrinh
		{
			get
			{
				return this._LoaiChuongTrinh;
			}
			set
			{
				if ((this._LoaiChuongTrinh != value))
				{
					this.OnLoaiChuongTrinhChanging(value);
					this.SendPropertyChanging();
					this._LoaiChuongTrinh = value;
					this.SendPropertyChanged("LoaiChuongTrinh");
					this.OnLoaiChuongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(50)")]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTieu", DbType="Int")]
		public System.Nullable<int> ChiTieu
		{
			get
			{
				return this._ChiTieu;
			}
			set
			{
				if ((this._ChiTieu != value))
				{
					this.OnChiTieuChanging(value);
					this.SendPropertyChanging();
					this._ChiTieu = value;
					this.SendPropertyChanged("ChiTieu");
					this.OnChiTieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocPhi", DbType="Int")]
		public System.Nullable<int> HocPhi
		{
			get
			{
				return this._HocPhi;
			}
			set
			{
				if ((this._HocPhi != value))
				{
					this.OnHocPhiChanging(value);
					this.SendPropertyChanging();
					this._HocPhi = value;
					this.SendPropertyChanged("HocPhi");
					this.OnHocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaNganh", DbType="NVarChar(MAX)")]
		public string MoTaNganh
		{
			get
			{
				return this._MoTaNganh;
			}
			set
			{
				if ((this._MoTaNganh != value))
				{
					this.OnMoTaNganhChanging(value);
					this.SendPropertyChanging();
					this._MoTaNganh = value;
					this.SendPropertyChanged("MoTaNganh");
					this.OnMoTaNganhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinKhoa")]
	public partial class ThongTinKhoa
	{
		
		private string _TenKhoa;
		
		private string _GioiThieu;
		
		public ThongTinKhoa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(50)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this._TenKhoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(MAX)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this._GioiThieu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinNguoiDung")]
	public partial class ThongTinNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _LoaiNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoaiNguoiDungChanging(string value);
    partial void OnLoaiNguoiDungChanged();
    #endregion
		
		public ThongTinNguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(20)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(20)", IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguoiDung", DbType="NVarChar(20)")]
		public string LoaiNguoiDung
		{
			get
			{
				return this._LoaiNguoiDung;
			}
			set
			{
				if ((this._LoaiNguoiDung != value))
				{
					this.OnLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._LoaiNguoiDung = value;
					this.SendPropertyChanged("LoaiNguoiDung");
					this.OnLoaiNguoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinNhapHoc")]
	public partial class ThongTinNhapHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NoiDungNhapHoc;
		
		private string _BuocSo;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoiDungNhapHocChanging(string value);
    partial void OnNoiDungNhapHocChanged();
    partial void OnBuocSoChanging(string value);
    partial void OnBuocSoChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public ThongTinNhapHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungNhapHoc", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string NoiDungNhapHoc
		{
			get
			{
				return this._NoiDungNhapHoc;
			}
			set
			{
				if ((this._NoiDungNhapHoc != value))
				{
					this.OnNoiDungNhapHocChanging(value);
					this.SendPropertyChanging();
					this._NoiDungNhapHoc = value;
					this.SendPropertyChanged("NoiDungNhapHoc");
					this.OnNoiDungNhapHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuocSo", DbType="NVarChar(50)")]
		public string BuocSo
		{
			get
			{
				return this._BuocSo;
			}
			set
			{
				if ((this._BuocSo != value))
				{
					this.OnBuocSoChanging(value);
					this.SendPropertyChanging();
					this._BuocSo = value;
					this.SendPropertyChanged("BuocSo");
					this.OnBuocSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinVanBan")]
	public partial class ThongTinVanBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TieuDe;
		
		private string _HinhAnh;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public ThongTinVanBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
